import { asset } from "@/src/lib/assets";
import type { Product, ProductFilter, SortOption } from "./ProductGrid.types";

export const products: Product[] = [
  {
    id: "hydraglass-pads",
    name: "HydraGlass™ Pads",
    price: 59,
    image: asset("/assets/waldor/products/product01.png"),
    secondImage: asset("/assets/waldor/products/product01_secondImage.png"),
    imageAlt: "HydraGlass™ Pads",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-longevity-pads?variant=54047116427528",
    variantLabel: "60 pads · pre-soaked",
    description: [
      "HydraGlass™ Pads are pre-soaked with a concentrated blend of hyaluronic acid and longevity peptides, designed to hydrate, refine and prep the skin in seconds.",
      "Each pad delivers an even layer of active serum across the face, smoothing texture and locking in moisture before the rest of your routine.",
    ],
    keyBenefits: [
      "Deeply hydrates and plumps the skin",
      "Refines texture and smooths fine lines",
      "Preps skin for better product absorption",
      "Convenient, mess-free daily use",
      "Gentle enough for sensitive skin",
    ],
  },
  {
    id: "exosome-peptide-serum",
    name: "Exosome Peptide Stem Cell Serum 5ml",
    price: 99,
    image: asset("/assets/waldor/products/product02.png"),
    secondImage: asset("/assets/waldor/products/product02_secondImage.png"),
    imageAlt: "Exosome Peptide Stem Cell Serum 5ml",
    category: "skin-care",
    href: "https://www.waldor.skin/products/exosome-peptide-stem-cell-serum-5ml?variant=54047107842312",
    badge: "BESTSELLER",
    variantLabel: "5ml · two-part system",
    description: [
      "Our Exosome Peptide Stem Cell Serum is formulated using freeze dried plant derived exosomes, preserved in powder form to maintain maximum stability and potency. The exosome powder is freshly activated by mixing with the accompanying peptide rich serum, creating a powerful regenerative formula designed to support skin renewal and repair.",
      "This two component system ensures that the active ingredients remain highly effective until the moment of activation. Once mixed, the serum delivers exosomes, peptides, hyaluronic acid, and collagen supporting actives directly to the skin to improve hydration, strengthen the skin barrier, and promote visible skin rejuvenation.",
      "The lightweight formula absorbs quickly and helps improve overall skin quality, leaving the skin looking smoother, healthier, and more radiant.",
    ],
    keyBenefits: [
      "Supports skin regeneration and cellular renewal",
      "Stimulates collagen production and improves elasticity",
      "Deeply hydrates and strengthens the skin barrier",
      "Improves skin texture and smoothness",
      "Promotes brighter, healthier-looking skin",
      "Calms sensitive or stressed skin",
    ],
    usageNote:
      "Two-component system — activate the exosome powder before first use. Manufactured in South Korea under strict quality control.",
  },
  {
    id: "hydraglass-collection",
    name: "HydraGlass™ Collection",
    price: 159,
    image: asset("/assets/waldor/products/product03.png"),
    secondImage: asset("/assets/waldor/products/product03_secondImage.png"),
    imageAlt: "HydraGlass™ Collection",
    category: "skin-care",
    href: "https://www.waldor.skin/products/korean-hydraglass%E2%84%A2-collection?variant=53383412842760",
    badge: "SET",
    variantLabel: "4-piece set",
    description: [
      "The HydraGlass™ Collection brings together our signature cleanser, serum, cream and eye lift cream in one complete routine.",
      "Formulated to work together, each step builds on the last — cleansing, hydrating, firming and brightening for a full glass-skin result.",
    ],
    keyBenefits: [
      "Complete 4-step glass-skin routine",
      "Formulated to layer seamlessly",
      "Hydrates, firms and brightens",
      "Ideal for first-time HydraGlass™ users",
      "Better value than buying each product separately",
    ],
  },
  {
    id: "hydraglass-cream",
    name: "HydraGlass™ Cream",
    price: 59,
    image: asset("/assets/waldor/products/product04.png"),
    secondImage: asset("/assets/waldor/products/product04_secondImage.png"),
    imageAlt: "HydraGlass™ Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-cream?variant=53374587961608",
    variantLabel: "50ml",
    description: [
      "A rich, barrier-supporting moisturiser formulated with Korean bio-fermented actives to lock in hydration and reinforce the skin's natural glow.",
      "Lightweight yet nourishing, it absorbs quickly without leaving residue, leaving skin soft, smooth and visibly plumper.",
    ],
    keyBenefits: [
      "Deeply moisturises and softens skin",
      "Strengthens the skin barrier",
      "Supports a smoother, glass-skin finish",
      "Lightweight, fast-absorbing texture",
      "Suitable for daily AM/PM use",
    ],
  },
  {
    id: "hydraglass-serum",
    name: "HydraGlass™ Serum",
    price: 69,
    image: asset("/assets/waldor/products/product05.png"),
    secondImage: asset("/assets/waldor/products/product05_secondImage.png"),
    imageAlt: "HydraGlass™ Serum",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-serum?variant=53374495850760",
    variantLabel: "30ml",
    description: [
      "A concentrated hydration serum formulated with multi-molecular hyaluronic acid to restore moisture at every layer of the skin.",
      "Its lightweight, fast-absorbing texture delivers an instant glow while supporting long-term skin resilience.",
    ],
    keyBenefits: [
      "Multi-depth hydration with hyaluronic acid",
      "Instantly boosts radiance",
      "Strengthens skin barrier over time",
      "Lightweight, non-greasy texture",
      "Layers well under moisturiser",
    ],
  },
  {
    id: "hydraglass-eye-lift-cream",
    name: "HydraGlass™ Eye Lift Cream",
    price: 89,
    image: asset("/assets/waldor/products/product06.png"),
    secondImage: asset("/assets/waldor/products/product06_secondImage.png"),
    imageAlt: "HydraGlass™ Eye Lift Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-eye-lift-cream?variant=53374448861448",
    variantLabel: "15ml",
    description: [
      "A targeted eye cream formulated to firm, brighten and smooth the delicate under-eye area.",
      "Peptides and hydrating actives work together to reduce the appearance of fine lines and puffiness for a rested, lifted look.",
    ],
    keyBenefits: [
      "Firms and smooths the eye area",
      "Reduces the look of puffiness",
      "Brightens dark circles over time",
      "Hydrates without heaviness",
      "Gentle formula for delicate skin",
    ],
  },
  {
    id: "hydraglass-cleanser",
    name: "HydraGlass™ Cleanser",
    price: 39,
    image: asset("/assets/waldor/products/product07.png"),
    secondImage: asset("/assets/waldor/products/product07_secondImage.png"),
    imageAlt: "HydraGlass™ Cleanser",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass-cleanser?variant=53306421313800",
    variantLabel: "150ml",
    description: [
      "A gentle, non-stripping cleanser that removes impurities and makeup while preserving the skin's natural moisture barrier.",
      "Formulated to prep skin for the rest of your HydraGlass™ routine, leaving it soft, calm and ready to absorb active ingredients.",
    ],
    keyBenefits: [
      "Removes impurities without stripping skin",
      "Preserves the skin's moisture barrier",
      "Preps skin for serums and creams",
      "Suitable for daily use",
      "Leaves skin soft and calm",
    ],
  },
  {
    id: "microneedle-longevity-cream",
    name: "Microneedle Longevity Cream",
    price: 89,
    image: asset("/assets/waldor/products/product08.png"),
    secondImage: asset("/assets/waldor/products/product08_secondImage.png"),
    imageAlt: "Microneedle Longevity Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/microneedle-longevity-bottle?variant=53297631854856",
    variantLabel: "50ml",
    description: [
      "A next-generation cream combining dissolving microneedle technology with longevity actives to deliver ingredients deeper into the skin.",
      "Formulated with peptides and regenerative compounds to support firmness, elasticity and a more youthful complexion over time.",
    ],
    keyBenefits: [
      "Enhanced ingredient delivery via microneedle technology",
      "Supports firmness and elasticity",
      "Promotes long-term skin renewal",
      "Targets early signs of ageing",
      "Suitable for nightly use",
    ],
  },
  {
    id: "glow-facial-mask",
    name: "GLOW Facial Mask",
    price: 10,
    image: asset("/assets/waldor/products/product09.png"),
    secondImage: asset("/assets/waldor/products/product09_secondImage.png"),
    imageAlt: "GLOW Facial Mask",
    category: "skin-care",
    href: "https://www.waldor.skin/products/glow-facial-mask?variant=54590813405448",
    variantLabel: "1 sheet · single use",
    description: [
      "An illuminating sheet mask infused with brightening and hydrating actives for an instant, radiant glow.",
      "Perfect as a pre-event treatment or weekly ritual to refresh tired, dull-looking skin.",
    ],
    keyBenefits: [
      "Instantly brightens and hydrates",
      "Refreshes dull, tired-looking skin",
      "Lightweight, fast-absorbing essence",
      "Ideal pre-event treatment",
      "Single-use, mess-free application",
    ],
  },
  {
    id: "lift-facial-mask",
    name: "Lift Facial Mask",
    price: 10,
    image: asset("/assets/waldor/products/product10.png"),
    secondImage: asset("/assets/waldor/products/product10_secondImage.png"),
    imageAlt: "Lift Facial Mask",
    category: "skin-care",
    href: "https://www.waldor.skin/products/lift-facial-mask?variant=54592956170504",
    variantLabel: "1 sheet · single use",
    description: [
      "A firming sheet mask designed to lift, tighten and smooth the complexion in just one use.",
      "Infused with peptides and toning actives, it leaves skin looking visibly contoured and refreshed.",
    ],
    keyBenefits: [
      "Visibly lifts and firms skin",
      "Smooths the appearance of fine lines",
      "Tones and refreshes complexion",
      "Quick, single-use treatment",
      "Ideal before special occasions",
    ],
  },
];

export const filterTabs: { label: string; value: ProductFilter }[] = [
  { label: "All", value: "all" },
  { label: "Skin Care", value: "skin-care" },
  { label: "Merch", value: "merch" },
];

export const sortOptions: { label: string; value: SortOption }[] = [
  { label: "Featured", value: "featured" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Name: A to Z", value: "name-asc" },
];
